name = "Dark Shark v3"
port = 44445

center_of_mass = [0.0, -0.07, 0.0]
motor_amperage_budget = 25.0
jerk_limit = 40.0

imu_offset = { yaw = 0.0, pitch = 0.0, roll = 180.0 }

[pid_configs]
Depth = { kp = 100.0, ki = 5.0, kd = 1.5, max_integral = 2.5, max_output = 25.0, i_zone = 0.25, d_alpha = 0.8 }
Yaw = { kp = 0.12, ki = 0.03, kd = 0.07, max_integral = 20.0, max_output = 5.0, i_zone = 10.0, d_alpha = 0.3 }
Pitch = { kp = 0.12, ki = 0.1, kd = 0.07, max_integral = 40.0, max_output = 5.0, i_zone = 30.0, d_alpha = 0.3 }
Roll = { kp = 0.07, ki = 0.03, kd = 0.05, max_integral = 40.0, max_output = 5.0, i_zone = 10.0, d_alpha = 0.3 }

[motor_config.Custom.motors.BackRightBottom]
channel = { PwmChannel = 4 }
position = [0.16586998298392233, -0.1847582499, -0.07966385632084612]
orientation = [0.3653688221537718, 0.8681561970388947, -0.3358726564353363]
direction = "CounterClockwise"

# Mirror of BackRightBottom
[motor_config.Custom.motors.BackLeftBottom]
channel = { PwmChannel = 1 }
position = [-0.16586998298392233, -0.1847582499, -0.07966385632084612]
orientation = [-0.3653688221537718, 0.8681561970388947, -0.3358726564353363]
direction = "Clockwise"

[motor_config.Custom.motors.BackRightTop]
channel = { PwmChannel = 5 }
position = [0.16531173024124723, -0.1523311155, 0.07974266168755904]
orientation = [-0.29416119788223927, 0.8196981925098801, 0.4914916711975105]
direction = "CounterClockwise"

# Mirror of BackRightTop
[motor_config.Custom.motors.BackLeftTop]
channel = { PwmChannel = 2 }
position = [-0.16531173024124723, -0.1523311155, 0.07974266168755904]
orientation = [0.29416119788223927, 0.8196981925098801, 0.4914916711975105]
direction = "Clockwise"

[motor_config.Custom.motors.FrontRight]
channel = { PwmChannel = 3 }
position = [0.16549094637027176, 0.1163957308, 0.0]
orientation = [0.5086841141129421, -0.3340963555185603, 0.7934860410103929]
direction = "CounterClockwise"

# Mirror of FrontRight
[motor_config.Custom.motors.FrontLeft]
channel = { PwmChannel = 0 }
position = [-0.16549094637027176, 0.1163957308, 0.0]
orientation = [-0.5086841141129421, -0.3340963555185603, 0.7934860410103929]
direction = "Clockwise"

[servo_config.servos]
FrontCameraRotate = { channel = { PwmChannel = 15 }, signal_type = "Position", control_mode = "FirstOrder", camera = "Front" }
Claw1 = { channel = { DcChannel = 0 }, signal_type = "Velocity", constraints = { min = -1.0, max = 1.0 }, slew_rate = { Percent = 5.0 } }
Claw2 = { channel = { DcChannel = 1 }, signal_type = "Velocity", constraints = { min = -1.0, max = 1.0 }, slew_rate = { Percent = 5.0 } }
Claw3 = { channel = { DcChannel = 2 }, signal_type = "Velocity", constraints = { min = -1.0, max = 1.0 }, slew_rate = { Percent = 5.0 } }
Lights = { channel = { DcChannel = 3 }, signal_type = "Position", control_mode = "FirstOrder", constraints = { min = 0.0, max = 0.75 } }


[cameras."/dev/video2"]
name = "Top Left"
transform = { position = { x = 0.0, y = 0.0, z = 0.0 }, rotation = { yaw = 0.0, pitch = 0.0, roll = 0.0 } }
movement_rotation = { yaw = -90.0, pitch = 0.0, roll = 0.0 }

[cameras."/dev/video6"]
name = "Top Right"
transform = { position = { x = 0.0, y = 0.0, z = 0.0 }, rotation = { yaw = 180.0, pitch = 0.0, roll = 0.0 } }
movement_rotation = { yaw = 90.0, pitch = 0.0, roll = 0.0 }

[cameras."/dev/video10"]
name = "Front Bottom"
transform = { position = { x = 0.0, y = 0.0, z = 0.0 }, rotation = { yaw = 0.0, pitch = 0.0, roll = 0.0 } }

[cameras."/dev/video14"]
name = "Bottom Right"
transform = { position = { x = 0.0, y = 0.0, z = 0.0 }, rotation = { yaw = 180.0, pitch = 0.0, roll = 0.0 } }

[cameras."/dev/video18"]
name = "Bottom"
transform = { position = { x = 0.0, y = 0.0, z = 0.0 }, rotation = { yaw = 180.0, pitch = 0.0, roll = 0.0 } }

[cameras."/dev/video41"]
name = "Front"
transform = { position = { x = 0.0, y = 0.0, z = 0.0 }, rotation = { yaw = 180.0, pitch = 0.0, roll = 0.0 } }
