name = "Dark Shark v3"
port = 44445

center_of_mass = [0.0, -0.07, 0.0]
motor_amperage_budget = 25.0
jerk_limit = 40.0

imu_offset = { yaw = 0.0, pitch = 0.0, roll = 180.0 }

[pid_configs]
Depth = { kp = 100.0, ki = 5.0, kd = 1.5, max_integral = 10.0, max_output = 25.0, i_zone = 0.25 }
Yaw = { kp = 0.3, ki = 0.01, kd = 0.05, max_integral = 10.0, max_output = 5.0, i_zone = 1.0 }
Pitch = { kp = 0.25, ki = 0.015, kd = 0.07, max_integral = 60.0, max_output = 5.0, i_zone = 1.0 }
Roll = { kp = 0.15, ki = 0.01, kd = 0.05, max_integral = 40.0, max_output = 5.0, i_zone = 1.0 }

[motor_config.Custom.motors.BackRightBottom]
channel = { PwmChannel = 4 }
position = [0.16586998298392233, -0.1847582499, -0.07966385632084612]
orientation = [0.3653688221537718, 0.8681561970388947, -0.3358726564353363]
direction = "CounterClockwise"

# Mirror of BackRightBottom
[motor_config.Custom.motors.BackLeftBottom]
channel = { PwmChannel = 1 }
position = [-0.16586998298392233, -0.1847582499, -0.07966385632084612]
orientation = [-0.3653688221537718, 0.8681561970388947, -0.3358726564353363]
direction = "Clockwise"

[motor_config.Custom.motors.BackRightTop]
channel = { PwmChannel = 5 }
position = [0.16531173024124723, -0.1523311155, 0.07974266168755904]
orientation = [-0.29416119788223927, 0.8196981925098801, 0.4914916711975105]
direction = "CounterClockwise"

# Mirror of BackRightTop
[motor_config.Custom.motors.BackLeftTop]
channel = { PwmChannel = 2 }
position = [-0.16531173024124723, -0.1523311155, 0.07974266168755904]
orientation = [0.29416119788223927, 0.8196981925098801, 0.4914916711975105]
direction = "Clockwise"

[motor_config.Custom.motors.FrontRight]
channel = { PwmChannel = 3 }
position = [0.16549094637027176, 0.1163957308, 0.0]
orientation = [0.5086841141129421, -0.3340963555185603, 0.7934860410103929]
direction = "CounterClockwise"

# Mirror of FrontRight
[motor_config.Custom.motors.FrontLeft]
channel = { PwmChannel = 0 }
position = [-0.16549094637027176, 0.1163957308, 0.0]
orientation = [-0.5086841141129421, -0.3340963555185603, 0.7934860410103929]
direction = "Clockwise"

[servo_config.servos]
FrontCameraRotate = { channel = { PwmChannel = 15 }, signal_type = "Position", control_mode = "FirstOrder", camera = "Front" }
Claw1 = { channel = { DcChannel = 0 }, signal_type = "Velocity", constraints = { min = -0.8, max = 0.8 } }
Claw2 = { channel = { DcChannel = 1 }, signal_type = "Velocity", constraints = { min = -0.8, max = 0.8 } }
Claw3 = { channel = { DcChannel = 2 }, signal_type = "Velocity", constraints = { min = -0.8, max = 0.8 } }
Lights = { channel = { DcChannel = 3 }, signal_type = "Position", control_mode = "FirstOrder", constraints = { min = 0.0, max = 0.75 } }


# [cameras."/dev/video2"]
# name = "Front"
# transform = { position = { x = 0.0, y = 1.0, z = 0.0 }, rotation = { yaw = 0.0, pitch = 0.0, roll = 0.0 } }
#
# [cameras."/dev/video6"]
# name = "Top"
# transform = { position = { x = 0.0, y = 0.0, z = 1.0 }, rotation = { yaw = 0.0, pitch = -90.0, roll = 0.0 } }
#
# [cameras."/dev/video10"]
# name = "A"
# transform = { position = { x = 0.0, y = 0.0, z = -1.0 }, rotation = { yaw = 0.0, pitch = 90.0, roll = 0.0 } }
#
# [cameras."/dev/video14"]
# name = "B"
# transform = { position = { x = 0.0, y = -1.0, z = 0.0 }, rotation = { yaw = -180.0, pitch = 0.0, roll = 0.0 } }
#
# [cameras."/dev/video18"]
# name = "C"
# transform = { position = { x = 1.0, y = 0.0, z = 0.0 }, rotation = { yaw = -90.0, pitch = 0.0, roll = 0.0 } }
