[package]
name = "stable_hashmap"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_reflect = { workspace = true, optional = true }

ahash = { workspace = true }

[features]
reflect = ["dep:bevy_reflect"]
