[build]
# rustflags = ["-Z", "threads=16"]

# https://chacin.dev/posts/cross-compiling-rust-for-the-raspberry-pi/
# Pi 5
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-none-linux-gnu-gcc"
runner = "./scripts/rpi-runner.sh"

# Pi 2/3/4
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-none-linux-gnueabihf-gcc"
runner = "./scripts/rpi-runner.sh"

